# -*- coding: utf-8 -*-
"""TestImagesToEnsemble.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165C2G_52SsPQdcwxvxynqJVFnyRDjYfQ
"""

import os
import shutil

#source files, make sure the name of your test folders are "Bottom", "Side", and "Top"
#Test folders are from the training Output, just copy the files to your "Bottom" "Side" and "Top" folder depending on the orientation of the training

source_directories = {
    'Bottom': 'D:/Files for Ensemble new/Test Images 3 inputs/Bottom',
    'Top': 'D:/Files for Ensemble new/Test Images 3 inputs/Top',
    'Side': 'D:/Files for Ensemble new/Test Images 3 inputs/Side',
}
destination_directory = 'D:/Files for Ensemble new/Test Images 3 inputs/Test Set Ensemble/' #Directory where you want to save your test images and arrange in preparation to ensemble

# Define the target subfolders(Do not edit, this should point to the folders inside the data
subfolders = ['Export', 'Local', 'Reject']

# Function to ensure the destination subfolder exists and return its path
def get_next_subfolder_path(dest_dir, count):
    subfolder_name = f"m{count}"
    subfolder_path = os.path.join(dest_dir, subfolder_name)
    os.makedirs(subfolder_path, exist_ok=True)
    return subfolder_path

# Function to copy and rename images( will rename each to, img1 for bottom,img2 for side and img3 for top)
def copy_and_rename_images(source_dir, dest_dir, image_name, counter):
    for filename in os.listdir(source_dir):
        if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
            new_folder_name = f"m{counter}"
            new_folder_path = os.path.join(dest_dir, new_folder_name)
            os.makedirs(new_folder_path, exist_ok=True)
            new_filename = f"img{image_name}.jpg"
            dest_path = os.path.join(new_folder_path, new_filename)
            source_path = os.path.join(source_dir, filename)
            shutil.copy(source_path, dest_path)
            counter += 1
    return counter

# Process each source folder (to process individual images and move to the destination folder)
for folder_name, folder_path in source_directories.items():
    for subfolder in subfolders:
        subfolder_path = os.path.join(folder_path, subfolder)
        if os.path.exists(subfolder_path):
            dest_subfolder_path = os.path.join(destination_directory, subfolder)
            os.makedirs(dest_subfolder_path, exist_ok=True)
            counter = 1
            if folder_name == 'Top':
                counter = copy_and_rename_images(subfolder_path, dest_subfolder_path, 1, counter)
            elif folder_name == 'Side':
                counter = copy_and_rename_images(subfolder_path, dest_subfolder_path, 2, counter)
            elif folder_name == 'Bottom':
                counter = copy_and_rename_images(subfolder_path, dest_subfolder_path, 3, counter)

print("Images have been successfully copied and renamed.")